<?php

/**
 * @file
 * menu_uuid module.
 */

module_load_include('inc', 'menu_uuid', 'menu_uuid');

/**
 * Implements hook_menu_link_insert().
 */
function menu_uuid_menu_link_insert() {
  menu_uuid_sync();
}

/**
 * Loads a menu item by UUID.
 */
function menu_link_uuid_load($uuid) {
  $mlid = db_select('menu_links', 'ml')->fields('ml', array('mlid'))->condition('uuid', $uuid)->execute()->fetchField();
  return menu_link_load($mlid);
}